# -*- coding: utf-8 -*-
"""Credit_card_fraud_detection_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DHliK-YMgOLjxvbCv9H88OlqVxkq-fJo

# Problem Statement:
Financial institutions need to detect fraudulent card transactions quickly while minimizing false positives for legitimate
customers. The project requires learners to build a fraud detection model for highly imbalanced data and deploy it as
a scoring service.

# Project objective
 Develop a fraud detection pipeline that predicts fraud probability, evaluates performance using imbalanced
classification metrics, and exposes predictions through a simple API or dashboard.
"""

import pandas as pd

df = pd.read_csv('/content/creditcard.csv')
display(df[['Time', 'Amount'] + [f'V{i}' for i in range(1, 29)] + ['Class']].head())

class_distribution = df['Class'].value_counts()
print('Class Distribution:\n', class_distribution)
print('\nPercentage of each class:\n', class_distribution / len(df) * 100)

from sklearn.model_selection import train_test_split

# Separate features (X) and target (y)
X = df.drop('Class', axis=1)
y = df['Class']

# Create stratified train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

print(f'X_train shape: {X_train.shape}')
print(f'y_train shape: {y_train.shape}')
print(f'X_test shape: {X_test.shape}')
print(f'y_test shape: {y_test.shape}')

from sklearn.preprocessing import StandardScaler

# Initialize StandardScaler
scaler = StandardScaler()

# Scale 'Time' and 'Amount' features only from the training data
X_train_scaled = X_train.copy()
X_test_scaled = X_test.copy()

X_train_scaled[['Time', 'Amount']] = scaler.fit_transform(X_train[['Time', 'Amount']])
X_test_scaled[['Time', 'Amount']] = scaler.transform(X_test[['Time', 'Amount']])

print('Scaled X_train head:')
display(X_train_scaled.head())
print('\nScaled X_test head:')
display(X_test_scaled.head())

import matplotlib.pyplot as plt
import seaborn as sns

# Visualize transaction amount patterns for fraudulent vs. non-fraudulent transactions
plt.figure(figsize=(10, 6))
sns.histplot(df[df['Class'] == 0]['Amount'], color='green', bins=50, alpha=0.5, stat='density', label='Non-Fraudulent')
sns.histplot(df[df['Class'] == 1]['Amount'], color='red', bins=50, alpha=0.5, stat='density', label='Fraudulent')
plt.title('Distribution of Transaction Amount by Class')
plt.xlabel('Amount')
plt.ylabel('Density')
plt.yscale('log') # Use log scale for y-axis due to imbalance
plt.legend()
plt.show()

# Also look at descriptive statistics for amount for both classes
print('\nDescriptive statistics for Amount (Non-Fraudulent):')
display(df[df['Class'] == 0]['Amount'].describe())
print('\nDescriptive statistics for Amount (Fraudulent):')
display(df[df['Class'] == 1]['Amount'].describe())

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

# Initialize Logistic Regression model
# Set class_weight='balanced' to handle imbalance, or we can use SMOTE later
model_lr = LogisticRegression(solver='liblinear', random_state=42, class_weight='balanced')

# Train the model on scaled training data
model_lr.fit(X_train_scaled, y_train)

# Make predictions on the scaled test data
y_pred_lr = model_lr.predict(X_test_scaled)
y_prob_lr = model_lr.predict_proba(X_test_scaled)[:, 1]

# Calculate the confusion matrix
cm = confusion_matrix(y_test, y_pred_lr)

# Plot the confusion matrix
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', cbar=False,
            xticklabels=['Non-Fraud (0)', 'Fraud (1)'],
            yticklabels=['Non-Fraud (0)', 'Fraud (1)'])
plt.title('Confusion Matrix for Logistic Regression')
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.show()

from sklearn.metrics import classification_report

# Generate a classification report
report = classification_report(y_test, y_pred_lr, target_names=['Non-Fraud (0)', 'Fraud (1)'])
print(report)

"""The classification report provides a detailed view of the model's performance:

Precision (Fraud): 0.06. This means that when the model predicts a transaction is fraudulent, it is only correct 6% of the time. This is a very low precision, indicating a high number of false positives (legitimate transactions incorrectly flagged as fraud).

Recall (Fraud): 0.92. This means the model correctly identifies 92% of all actual fraudulent transactions. This is a good recall, meaning it's effective at catching most fraud instances.

F1-Score (Fraud): 0.11. The F1-score is the harmonic mean of precision and recall. A low F1-score here (0.11) reflects the poor balance between precision and recall for the fraudulent class.

Precision (Non-Fraud): 1.00. The model is almost perfect at correctly identifying non-fraudulent transactions when it predicts them as such.

Recall (Non-Fraud): 0.98. The model correctly identifies 98% of all actual non-fraudulent transactions.

Accuracy: 0.98. While overall accuracy is high, it's a misleading metric in highly imbalanced datasets like this, as it's heavily skewed by the majority class (non-fraudulent transactions).

In summary, the model does an excellent job of identifying legitimate transactions and catching most fraudulent ones (high recall for fraud). However, its very low precision for fraud suggests that it flags many non-fraudulent transactions as fraud, which could lead to significant operational overhead (e.g., false alarms, customer inconvenience). This trade-off between precision and recall is common in imbalanced datasets and is something we might want to optimize further depending on the business requirements (e.g., minimizing false positives vs. maximizing fraud detection).
"""

from sklearn.metrics import precision_recall_curve, auc
import matplotlib.pyplot as plt

# Calculate precision, recall, and thresholds
precision, recall, thresholds = precision_recall_curve(y_test, y_prob_lr)

# Calculate Average Precision (AP)
AP = auc(recall, precision)

# Plot the Precision-Recall curve
plt.figure(figsize=(10, 6))
plt.plot(recall, precision, label=f'Logistic Regression (AP = {AP:.2f})')
plt.xlabel('Recall')
plt.ylabel('Precision')
plt.title('Precision-Recall Curve')
plt.legend(loc='best')
plt.grid(True)
plt.show()

"""### Adjusting Decision Threshold to Improve Precision

To improve the precision for detecting fraudulent transactions, we can adjust the classification threshold. By increasing the threshold, the model will be more conservative in flagging transactions as fraudulent, potentially reducing false positives at the cost of some recall.
"""

# Define a new decision threshold (e.g., 0.7 to increase precision)
new_threshold = 0.7  # You can adjust this value to explore different trade-offs

# Generate new predictions based on the adjusted threshold
y_pred_lr_tuned = (y_prob_lr >= new_threshold).astype(int)

# Calculate the confusion matrix with the new threshold
cm_tuned = confusion_matrix(y_test, y_pred_lr_tuned)

# Plot the new confusion matrix
plt.figure(figsize=(8, 6))
sns.heatmap(cm_tuned, annot=True, fmt='d', cmap='Blues', cbar=False,
            xticklabels=['Non-Fraud (0)', 'Fraud (1)'],
            yticklabels=['Non-Fraud (0)', 'Fraud (1)'])
plt.title(f'Confusion Matrix for Logistic Regression (Threshold={new_threshold})')
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.show()

from sklearn.metrics import classification_report

# Generate a classification report with the new threshold
report_tuned = classification_report(y_test, y_pred_lr_tuned, target_names=['Non-Fraud (0)', 'Fraud (1)'])
print(report_tuned)

"""### Build a Neural Network Classifier

Next, we will build a simple neural network using TensorFlow/Keras to see if it can improve upon the performance of the Logistic Regression model. We will use the same scaled data for training and evaluation.
"""

import tensorflow as tf
from tensorflow import keras
from sklearn.metrics import confusion_matrix, classification_report
import seaborn as sns
import matplotlib.pyplot as plt
from tensorflow.keras.callbacks import EarlyStopping # Import EarlyStopping

# Define the neural network architecture
model_nn = keras.Sequential([
    keras.layers.Input(shape=(X_train_scaled.shape[1],)), # Input layer, matches number of features
    keras.layers.Dense(64, activation='relu'),            # Hidden layer with 64 neurons and ReLU activation
    keras.layers.Dropout(0.3),                             # Dropout for regularization
    keras.layers.Dense(32, activation='relu'),            # Hidden layer with 32 neurons and ReLU activation
    keras.layers.Dropout(0.3),                             # Dropout for regularization
    keras.layers.Dense(1, activation='sigmoid')           # Output layer with 1 neuron and Sigmoid activation for binary classification
])

# Compile the model
model_nn.compile(
    optimizer=keras.optimizers.Adam(learning_rate=0.001),
    loss='binary_crossentropy',
    metrics=['accuracy', keras.metrics.Precision(), keras.metrics.Recall()]
)

# Display model summary
model_nn.summary()

# Define EarlyStopping callback
early_stopping = EarlyStopping(
    monitor='val_loss', # Monitor the validation loss
    patience=5,         # Number of epochs with no improvement after which training will be stopped
    restore_best_weights=True # Restore model weights from the epoch with the best value of the monitored quantity
)

# Train the model
history = model_nn.fit(
    X_train_scaled,
    y_train,
    epochs=20,
    batch_size=256,
    validation_split=0.2, # Use 20% of training data for validation
    class_weight={0: 1, 1: (len(y_train) / (2 * y_train.sum()))}, # Apply class weights to handle imbalance
    callbacks=[early_stopping], # Add the early stopping callback
    verbose=1
)

# Evaluate the model on the test set
loss, accuracy, precision_nn, recall_nn = model_nn.evaluate(X_test_scaled, y_test, verbose=0)

print(f'\nNeural Network Test Loss: {loss:.4f}')
print(f'Neural Network Test Accuracy: {accuracy:.4f}')
print(f'Neural Network Test Precision: {precision_nn:.4f}')
print(f'Neural Network Test Recall: {recall_nn:.4f}')

# Make predictions (probabilities)
y_prob_nn = model_nn.predict(X_test_scaled).flatten()

# Convert probabilities to binary predictions (default threshold 0.5)
y_pred_nn = (y_prob_nn > 0.5).astype(int)

# Calculate and plot the confusion matrix
cm_nn = confusion_matrix(y_test, y_pred_nn)

plt.figure(figsize=(8, 6))
sns.heatmap(cm_nn, annot=True, fmt='d', cmap='Blues', cbar=False,
            xticklabels=['Non-Fraud (0)', 'Fraud (1)'],
            yticklabels=['Non-Fraud (0)', 'Fraud (1)'])
plt.title('Confusion Matrix for Neural Network')
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.show()

# Generate a classification report
report_nn = classification_report(y_test, y_pred_nn, target_names=['Non-Fraud (0)', 'Fraud (1)'])
print('\nClassification Report for Neural Network:\n', report_nn)

"""### Adjusting Decision Threshold for Neural Network to Improve Precision

Similar to the Logistic Regression model, we can adjust the decision threshold for the Neural Network to achieve a better trade-off between precision and recall, especially if minimizing false positives is a priority.
"""

# Define a new decision threshold for the Neural Network (e.g., 0.7)
new_threshold_nn = 0.7  # You can adjust this value to explore different trade-offs

# Generate new predictions based on the adjusted threshold
y_pred_nn_tuned = (y_prob_nn >= new_threshold_nn).astype(int)

# Calculate the confusion matrix with the new threshold
cm_nn_tuned = confusion_matrix(y_test, y_pred_nn_tuned)

# Plot the new confusion matrix
plt.figure(figsize=(8, 6))
sns.heatmap(cm_nn_tuned, annot=True, fmt='d', cmap='Blues', cbar=False,
            xticklabels=['Non-Fraud (0)', 'Fraud (1)'],
            yticklabels=['Non-Fraud (0)', 'Fraud (1)'])
plt.title(f'Confusion Matrix for Neural Network (Threshold={new_threshold_nn})')
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.show()

"""Training Observations:

The training stopped prematurely at Epoch 12/20, which means Early Stopping activated, indicating that the validation loss did not improve for 5 consecutive epochs (patience=5).
This suggests that the model identified a point where it started to overfit or stopped improving on the validation set, and the best weights from a previous epoch were restored.
Neural Network Test Loss: 0.0275 Neural Network Test Accuracy: 0.9950 Neural Network Test Precision: 0.2438 Neural Network Test Recall: 0.8979

Confusion Matrix for Neural Network (Default Threshold 0.5) with Early Stopping:

True Negatives (Top-Left): 56,591 transactions were correctly identified as non-fraudulent.
False Positives (Top-Right): 273 non-fraudulent transactions were incorrectly classified as fraudulent.
False Negatives (Bottom-Left): 10 fraudulent transactions were incorrectly classified as non-fraudulent.
True Positives (Bottom-Right): 88 fraudulent transactions were correctly identified as fraudulent.
Classification Report for Neural Network (with Early Stopping):

Precision (Fraud): 0.24 (Increased from 0.19 without Early Stopping)
Recall (Fraud): 0.90 (Slightly increased from 0.89 without Early Stopping)
F1-Score (Fraud): 0.38 (Increased from 0.31 without Early Stopping)
Impact of Early Stopping:

By implementing Early Stopping, the model's performance has further improved, particularly in terms of precision for the fraud class. The number of False Positives has decreased from 381 to 273, which is a significant reduction. This means the model is now even better at avoiding false alarms, making it more practical for real-world application. The recall for fraud remains high (around 0.90), meaning it still catches most fraudulent transactions. The F1-score, which balances precision and recall, has also seen a substantial increase.

This demonstrates that Early Stopping effectively mitigated overfitting and helped the model achieve better generalization capabilities on unseen data.

### Exploring SMOTE for Class Imbalance

Beyond class weighting and threshold tuning, SMOTE (Synthetic Minority Over-sampling Technique) is another powerful method to address class imbalance. SMOTE works by creating synthetic samples from the minority class rather than just duplicating existing ones, which can help a model learn a more robust decision boundary.
"""

from imblearn.over_sampling import SMOTE

# Initialize SMOTE
smote = SMOTE(random_state=42)

# Apply SMOTE to the training data
X_train_smote, y_train_smote = smote.fit_resample(X_train_scaled, y_train)

print('Original training set shape:', y_train.shape)
print('SMOTE-oversampled training set shape:', y_train_smote.shape)
print('\nClass distribution after SMOTE:\n', pd.Series(y_train_smote).value_counts())

"""Now, let's train a Logistic Regression model on this SMOTE-oversampled training data and evaluate its performance on the original (unmodified) test set."""

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, classification_report
import seaborn as sns
import matplotlib.pyplot as plt

# Initialize Logistic Regression model (without class_weight as SMOTE has balanced the data)
model_lr_smote = LogisticRegression(solver='liblinear', random_state=42)

# Train the model on SMOTE-oversampled training data
model_lr_smote.fit(X_train_smote, y_train_smote)

# Make predictions on the original scaled test data
y_pred_lr_smote = model_lr_smote.predict(X_test_scaled)

# Calculate the confusion matrix
cm_lr_smote = confusion_matrix(y_test, y_pred_lr_smote)

# Plot the confusion matrix
plt.figure(figsize=(8, 6))
sns.heatmap(cm_lr_smote, annot=True, fmt='d', cmap='Blues', cbar=False,
            xticklabels=['Non-Fraud (0)', 'Fraud (1)'],
            yticklabels=['Non-Fraud (0)', 'Fraud (1)'])
plt.title('Confusion Matrix for Logistic Regression (with SMOTE)')
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.show()

# Generate a classification report
report_lr_smote = classification_report(y_test, y_pred_lr_smote, target_names=['Non-Fraud (0)', 'Fraud (1)'])
print('\nClassification Report for Logistic Regression (with SMOTE):\n', report_lr_smote)

"""## Hyperparameter Tuning for Logistic Regression with RandomizedSearchCV"""

from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import uniform

# Define the parameter distributions for RandomizedSearchCV
param_distributions_lr = {
    'C': uniform(loc=0.01, scale=100),
    'solver': ['liblinear', 'saga'],
    'penalty': ['l1', 'l2']
}

# Initialize Logistic Regression model with class_weight='balanced'
model_lr_rs_base = LogisticRegression(random_state=42, class_weight='balanced')

# Initialize RandomizedSearchCV
# Optimize for 'f1' score, as it balances precision and recall, crucial for imbalanced data
random_search_lr = RandomizedSearchCV(
    estimator=model_lr_rs_base,
    param_distributions=param_distributions_lr,
    n_iter=20, # Number of parameter settings that are sampled
    scoring='f1', # Metric to optimize
    cv=3, # 3-fold cross-validation
    verbose=2,
    random_state=42,
    n_jobs=-1 # Use all available CPU cores
)

# Fit RandomizedSearchCV to the scaled training data
random_search_lr.fit(X_train_scaled, y_train)

# Print the best parameters and the best score
print(f"\nBest parameters found: {random_search_lr.best_params_}")
print(f"Best F1-score found: {random_search_lr.best_score_:.4f}")

# Get the best model
best_model_lr_rs = random_search_lr.best_estimator_

# Make predictions with the best model
y_pred_lr_rs_tuned = best_model_lr_rs.predict(X_test_scaled)

# Calculate and plot the confusion matrix for the tuned model
cm_lr_rs_tuned = confusion_matrix(y_test, y_pred_lr_rs_tuned)

plt.figure(figsize=(8, 6))
sns.heatmap(cm_lr_rs_tuned, annot=True, fmt='d', cmap='Blues', cbar=False,
            xticklabels=['Non-Fraud (0)', 'Fraud (1)'],
            yticklabels=['Non-Fraud (0)', 'Fraud (1)'])
plt.title('Confusion Matrix for Tuned Logistic Regression (Random Search)')
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.show()

# Generate a classification report for the tuned model
report_lr_rs_tuned = classification_report(y_test, y_pred_lr_rs_tuned, target_names=['Non-Fraud (0)', 'Fraud (1)'])
print('\nClassification Report for Tuned Logistic Regression (Random Search):\n', report_lr_rs_tuned)

"""## Exporting the Tuned Logistic Regression Model"""

import joblib

# Define the filename for the exported model
lr_rs_model_filename = 'best_logistic_regression_rs_model.joblib'

# Save the best_model_lr_rs using joblib
joblib.dump(best_model_lr_rs, lr_rs_model_filename)

print(f"Tuned Logistic Regression model saved to {lr_rs_model_filename}")

"""### Training Neural Network with SMOTE-Oversampled Data

Now, let's train our Neural Network model using the SMOTE-oversampled training data (`X_train_smote`, `y_train_smote`). We will no longer need `class_weight` in the `fit` method as SMOTE has already balanced the classes.
"""

import tensorflow as tf
from tensorflow import keras
from sklearn.metrics import confusion_matrix, classification_report
import seaborn as sns
import matplotlib.pyplot as plt
from tensorflow.keras.callbacks import EarlyStopping

# Redefine the neural network architecture (to ensure a fresh start)
model_nn_smote = keras.Sequential([
    keras.layers.Input(shape=(X_train_smote.shape[1],)), # Input layer, matches number of features from SMOTE data
    keras.layers.Dense(64, activation='relu'),            # Hidden layer with 64 neurons and ReLU activation
    keras.layers.Dropout(0.3),                             # Dropout for regularization
    keras.layers.Dense(32, activation='relu'),            # Hidden layer with 32 neurons and ReLU activation
    keras.layers.Dropout(0.3),                             # Dropout for regularization
    keras.layers.Dense(1, activation='sigmoid')           # Output layer with 1 neuron and Sigmoid activation for binary classification
])

# Compile the model
model_nn_smote.compile(
    optimizer=keras.optimizers.Adam(learning_rate=0.001),
    loss='binary_crossentropy',
    metrics=['accuracy', keras.metrics.Precision(), keras.metrics.Recall()]
)

model_nn_smote.summary()

# Define EarlyStopping callback (same as before)
early_stopping_smote = EarlyStopping(
    monitor='val_loss',
    patience=5,
    restore_best_weights=True
)

# Train the model on SMOTE-oversampled data
history_smote = model_nn_smote.fit(
    X_train_smote,
    y_train_smote,
    epochs=20,
    batch_size=256,
    validation_split=0.2, # Use 20% of SMOTE training data for validation
    callbacks=[early_stopping_smote], # Add the early stopping callback
    verbose=1
)

# Evaluate the model on the original scaled test set
loss_smote, accuracy_smote, precision_nn_smote, recall_nn_smote = model_nn_smote.evaluate(X_test_scaled, y_test, verbose=0)

print(f'\nNeural Network (with SMOTE) Test Loss: {loss_smote:.4f}')
print(f'Neural Network (with SMOTE) Test Accuracy: {accuracy_smote:.4f}')
print(f'Neural Network (with SMOTE) Test Precision: {precision_nn_smote:.4f}')
print(f'Neural Network (with SMOTE) Test Recall: {recall_nn_smote:.4f}')

# Make predictions (probabilities)
y_prob_nn_smote = model_nn_smote.predict(X_test_scaled).flatten()

# Convert probabilities to binary predictions (default threshold 0.5)
y_pred_nn_smote = (y_prob_nn_smote > 0.5).astype(int)

# Calculate and plot the confusion matrix
cm_nn_smote = confusion_matrix(y_test, y_pred_nn_smote)

plt.figure(figsize=(8, 6))
sns.heatmap(cm_nn_smote, annot=True, fmt='d', cmap='Blues', cbar=False,
            xticklabels=['Non-Fraud (0)', 'Fraud (1)'],
            yticklabels=['Non-Fraud (0)', 'Fraud (1)'])
plt.title('Confusion Matrix for Neural Network (with SMOTE)')
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.show()

# Generate a classification report
report_nn_smote = classification_report(y_test, y_pred_nn_smote, target_names=['Non-Fraud (0)', 'Fraud (1)'])
print('\nClassification Report for Neural Network (with SMOTE):\n', report_nn_smote)

plt.figure(figsize=(10, 6))
plt.plot(history_smote.history['loss'], label='Training Loss (with SMOTE)')
plt.plot(history_smote.history['val_loss'], label='Validation Loss (with SMOTE)')
plt.title('Neural Network Training and Validation Loss (with SMOTE)')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()
plt.grid(True)
plt.show()

# Generate a classification report with the new threshold
report_nn_tuned = classification_report(y_test, y_pred_nn_tuned, target_names=['Non-Fraud (0)', 'Fraud (1)'])
print('\nClassification Report for Neural Network (Tuned Threshold):\n', report_nn_tuned)

plt.figure(figsize=(10, 6))
plt.plot(history.history['loss'], label='Training Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.title('Neural Network Training and Validation Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()
plt.grid(True)
plt.show()

from xgboost import XGBClassifier
from sklearn.metrics import confusion_matrix, classification_report
import seaborn as sns
import matplotlib.pyplot as plt

# Calculate the scale_pos_weight for XGBoost to handle class imbalance
scale_pos_weight_xgb = len(y_train[y_train == 0]) / len(y_train[y_train == 1])

# Initialize XGBoost Classifier
model_xgb = XGBClassifier(
    objective='binary:logistic',
    eval_metric='logloss',
    use_label_encoder=False, # Suppress warning
    random_state=42,
    n_estimators=100,
    learning_rate=0.1,
    scale_pos_weight=scale_pos_weight_xgb # Handle class imbalance
)

# Train the model on scaled training data
model_xgb.fit(X_train_scaled, y_train)

# Make predictions on the scaled test data
y_pred_xgb = model_xgb.predict(X_test_scaled)

# Calculate and plot the confusion matrix
cm_xgb = confusion_matrix(y_test, y_pred_xgb)

plt.figure(figsize=(8, 6))
sns.heatmap(cm_xgb, annot=True, fmt='d', cmap='Blues', cbar=False,
            xticklabels=['Non-Fraud (0)', 'Fraud (1)'],
            yticklabels=['Non-Fraud (0)', 'Fraud (1)'])
plt.title('Confusion Matrix for XGBoost Classifier')
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.show()

# Generate a classification report
report_xgb = classification_report(y_test, y_pred_xgb, target_names=['Non-Fraud (0)', 'Fraud (1)'])
print('\nClassification Report for XGBoost Classifier:\n', report_xgb)

"""XGBoost Classifier Performance:

Precision (Fraud): 0.78 (This is a significant improvement over previous models, meaning 78% of transactions flagged as fraudulent are truly fraudulent).
Recall (Fraud): 0.84 (The model identified 84% of all actual fraudulent transactions).
F1-Score (Fraud): 0.81 (This high F1-score indicates a strong balance between precision and recall for the fraud class, which is very good).
Confusion Matrix for XGBoost Classifier:

True Negatives: 56,841 (Correctly identified as non-fraudulent).
False Positives: 23 (Non-fraudulent transactions incorrectly flagged as fraudulent – a very low number!).
False Negatives: 16 (Fraudulent transactions missed by the model).
True Positives: 82 (Correctly identified as fraudulent).
This performance, especially the low number of false positives (23) while maintaining good recall (84), is the best we've seen so far among all models.

## Feature Importance of XGBoost Model
"""

import matplotlib.pyplot as plt
import seaborn as sns

# Get feature importances from the XGBoost model
feature_importances = model_xgb.feature_importances_

# Create a DataFrame for better visualization
# X_train_scaled.columns should be available from earlier steps
features_df = pd.DataFrame({
    'Feature': X_train_scaled.columns,
    'Importance': feature_importances
})

# Sort by importance in descending order
features_df = features_df.sort_values(by='Importance', ascending=False)

# Plot the top N feature importances
plt.figure(figsize=(12, 7))
sns.barplot(x='Importance', y='Feature', hue='Feature', data=features_df.head(10), palette='viridis', legend=False)
plt.title('Top 10 Feature Importances for XGBoost Classifier')
plt.xlabel('Importance (F-score)')
plt.ylabel('Feature')
plt.tight_layout()
plt.show()

print('\nTop 10 Feature Importances:\n', features_df.head(10))

"""The confusion matrix and classification report for the XGBoost model were already generated in the previous step. Here's a summary of its performance on the test set:

Confusion Matrix for XGBoost Classifier:

True Negatives: 56,841 (Correctly identified as non-fraudulent).
False Positives: 23 (Non-fraudulent transactions incorrectly flagged as fraudulent – a very low number!).
False Negatives: 16 (Fraudulent transactions missed by the model).
True Positives: 82 (Correctly identified as fraudulent).
Classification Report for XGBoost Classifier:

Precision (Fraud): 0.78
Recall (Fraud): 0.84
F1-Score (Fraud): 0.81
This performance is excellent, especially with the very low number of false positives (23) while maintaining strong recall (84%).

## Hyperparameter Tuning for XGBoost Model
"""

from sklearn.model_selection import GridSearchCV

# Define the parameter grid to search
param_grid = {
    'n_estimators': [100, 200],
    'learning_rate': [0.05, 0.1],
    'max_depth': [3, 5],
    'subsample': [0.7, 0.9],
    'colsample_bytree': [0.7, 0.9]
}

# Initialize XGBClassifier with imbalance handling and other base parameters
# We will let GridSearchCV handle n_estimators, learning_rate, max_depth, subsample, colsample_bytree
model_xgb_base = XGBClassifier(
    objective='binary:logistic',
    eval_metric='logloss',
    use_label_encoder=False, # Suppress warning
    random_state=42,
    scale_pos_weight=scale_pos_weight_xgb # Use the previously calculated scale_pos_weight
)

# Initialize GridSearchCV
# Scoring 'f1' is often good for imbalanced datasets, focusing on the positive class (fraud)
grid_search = GridSearchCV(estimator=model_xgb_base,
                           param_grid=param_grid,
                           scoring='f1',
                           cv=3, # Using 3-fold cross-validation
                           verbose=2,
                           n_jobs=-1) # Use all available CPU cores

# Fit GridSearchCV to the training data
grid_search.fit(X_train_scaled, y_train)

# Print the best parameters and the best score
print(f"\nBest parameters found: {grid_search.best_params_}")
print(f"Best F1-score found: {grid_search.best_score_:.4f}")

# Get the best model
best_model_xgb = grid_search.best_estimator_

# Make predictions with the best model
y_pred_xgb_tuned = best_model_xgb.predict(X_test_scaled)

# Calculate and plot the confusion matrix for the tuned model
cm_xgb_tuned = confusion_matrix(y_test, y_pred_xgb_tuned)

plt.figure(figsize=(8, 6))
sns.heatmap(cm_xgb_tuned, annot=True, fmt='d', cmap='Blues', cbar=False,
            xticklabels=['Non-Fraud (0)', 'Fraud (1)'],
            yticklabels=['Non-Fraud (0)', 'Fraud (1)'])
plt.title('Confusion Matrix for Tuned XGBoost Classifier')
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.show()

# Generate a classification report for the tuned model
report_xgb_tuned = classification_report(y_test, y_pred_xgb_tuned, target_names=['Non-Fraud (0)', 'Fraud (1)'])
print('\nClassification Report for Tuned XGBoost Classifier:\n', report_xgb_tuned)

"""The hyperparameter tuning for the XGBoost model using GridSearchCV has finished.

Best Parameters Found:

colsample_bytree: 0.9
learning_rate: 0.1
max_depth: 5
n_estimators: 200
subsample: 0.7
The GridSearchCV found an average F1-score of 0.8491 during cross-validation with these parameters.

Performance of the Tuned XGBoost Classifier on the Test Set:

Precision (Fraud): 0.85 (meaning 85% of transactions flagged as fraudulent are truly fraudulent).
Recall (Fraud): 0.84 (the model identified 84% of all actual fraudulent transactions).
F1-Score (Fraud): 0.84 (a very strong balance between precision and recall for fraud).
Confusion Matrix for Tuned XGBoost Classifier:

True Negatives: 56,849 (Correctly identified as non-fraudulent).
False Positives: 15 (Non-fraudulent transactions incorrectly flagged as fraudulent – even lower than the untuned model!).
False Negatives: 16 (Fraudulent transactions missed by the model).
True Positives: 82 (Correctly identified as fraudulent).
Comparing this to the initial XGBoost model (Precision: 0.78, Recall: 0.84, F1-Score: 0.81, False Positives: 23), the tuned model has achieved a notable improvement in precision for the fraud class while maintaining the same high recall. The number of false positives has been further reduced from 23 to 15, which is excellent!

## Exporting the Tuned XGBoost Model
"""

import joblib

# Define the filename for the exported model
model_filename = 'best_xgboost_model.joblib'

# Save the best_model_xgb using joblib
joblib.dump(best_model_xgb, model_filename)

print(f"Tuned XGBoost model saved to {model_filename}")

"""## Bayesian Optimization Hyperparameter Tuning for Neural Network Model"""

import sys

# Install Keras Tuner for hyperparameter optimization and Scikeras to wrap Keras models in a scikit-learn compatible estimator
!{sys.executable} -m pip install keras-tuner scikeras

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.callbacks import EarlyStopping
from sklearn.metrics import classification_report, confusion_matrix
from scikeras.wrappers import KerasClassifier
import keras_tuner as kt
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt


# Define a function to build the Keras model with hyperparameters as arguments
def build_model(hp):
    model = keras.Sequential()
    model.add(keras.layers.Input(shape=(X_train_scaled.shape[1],)))

    # Tune the number of hidden layers
    for i in range(hp.Int('num_hidden_layers', 1, 3)):
        model.add(keras.layers.Dense(
            units=hp.Int(f'units_{i}', min_value=32, max_value=128, step=32),
            activation='relu'
        ))
        model.add(keras.layers.Dropout(hp.Float(f'dropout_{i}', min_value=0.2, max_value=0.5, step=0.1)))

    model.add(keras.layers.Dense(1, activation='sigmoid'))

    # Tune the learning rate for the optimizer
    hp_learning_rate = hp.Choice('learning_rate', values=[1e-2, 1e-3, 1e-4])
    model.compile(
        optimizer=keras.optimizers.Adam(learning_rate=hp_learning_rate),
        loss='binary_crossentropy',
        metrics=['accuracy', keras.metrics.Precision(), keras.metrics.Recall()]
    )
    return model

# Initialize the Keras Tuner BayesianOptimization tuner
tuner = kt.BayesianOptimization(
    hypermodel=build_model,
    objective=kt.Objective('val_precision', direction='max'), # Optimize for validation precision
    max_trials=10, # Number of trials to run
    executions_per_trial=2, # Number of models to train for each trial to reduce variance
    overwrite=True,
    directory='keras_tuner_dir',
    project_name='nn_bayesian_tuning'
)

# Define EarlyStopping callback for the tuner's search process
early_stopping_tuner = EarlyStopping(
    monitor='val_loss',
    patience=3,
    restore_best_weights=True
)

# Get class weights to handle imbalance
class_weights_nn_tuning = {
    0: 1,
    1: (len(y_train) / (2 * y_train.sum()))
}

# Run the hyperparameter search
tuner.search(
    X_train_scaled,
    y_train,
    epochs=10,
    validation_split=0.2,
    callbacks=[early_stopping_tuner],
    class_weight=class_weights_nn_tuning,
    verbose=1
)

# Get the best hyperparameters
best_hps = tuner.get_best_hyperparameters(num_trials=1)[0]

print(f"\nBest hyperparameters found during Bayesian optimization:\n {best_hps.values}")

# Get the best model
best_model_nn = tuner.get_best_models(num_models=1)[0]

# Evaluate the best model on the test set
loss_best_nn, accuracy_best_nn, precision_best_nn, recall_best_nn = best_model_nn.evaluate(X_test_scaled, y_test, verbose=0)

print(f'\nBest Neural Network Test Loss: {loss_best_nn:.4f}')
print(f'Best Neural Network Test Accuracy: {accuracy_best_nn:.4f}')
print(f'Best Neural Network Test Precision: {precision_best_nn:.4f}')
print(f'Best Neural Network Test Recall: {recall_best_nn:.4f}')

# Make predictions (probabilities)
y_prob_best_nn = best_model_nn.predict(X_test_scaled).flatten()

# Convert probabilities to binary predictions (default threshold 0.5)
y_pred_best_nn = (y_prob_best_nn > 0.5).astype(int)

# Calculate and plot the confusion matrix
cm_best_nn = confusion_matrix(y_test, y_pred_best_nn)

plt.figure(figsize=(8, 6))
sns.heatmap(cm_best_nn, annot=True, fmt='d', cmap='Blues', cbar=False,
            xticklabels=['Non-Fraud (0)', 'Fraud (1)'],
            yticklabels=['Non-Fraud (0)', 'Fraud (1)'])
plt.title('Confusion Matrix for Best Tuned Neural Network (Bayesian Opt)')
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.show()

# Generate a classification report
report_best_nn = classification_report(y_test, y_pred_best_nn, target_names=['Non-Fraud (0)', 'Fraud (1)'])
print('\nClassification Report for Best Tuned Neural Network (Bayesian Opt):\n', report_best_nn)

"""## Exporting the Tuned Neural Network Model"""

import joblib

# Define the filename for the exported model
nn_model_filename = 'best_nn_model.joblib'

# Save the best_model_nn using joblib
joblib.dump(best_model_nn, nn_model_filename)

print(f"Tuned Neural Network model saved to {nn_model_filename}")

"""## Model Comparison: Logistic Regression vs. Neural Network vs. XGBoost"""

from sklearn.metrics import roc_auc_score, precision_recall_curve, auc, confusion_matrix, classification_report

# --- Define a function to get metrics for a model ---
def get_model_metrics(model, X_test, y_test, model_name):
    # Get probability predictions
    if hasattr(model, 'predict_proba'): # For scikit-learn models and KerasClassifier wrapper
        y_prob = model.predict_proba(X_test)[:, 1]
    elif hasattr(model, 'predict'): # For raw Keras Sequential model
        y_prob = model.predict(X_test).flatten()
    else:
        raise AttributeError("Model does not have 'predict_proba' or 'predict' method.")

    # Get binary predictions (using default threshold 0.5)
    y_pred = (y_prob > 0.5).astype(int)

    # Calculate confusion matrix
    cm = confusion_matrix(y_test, y_pred)
    tn, fp, fn, tp = cm.ravel()

    # Calculate Precision, Recall, F1-score for the positive class (fraud=1)
    report = classification_report(y_test, y_pred, output_dict=True, zero_division=0)
    precision_fraud = report['1']['precision']
    recall_fraud = report['1']['recall']
    f1_score_fraud = report['1']['f1-score']

    # Calculate PR-AUC
    precision_curve, recall_curve, _ = precision_recall_curve(y_test, y_prob)
    pr_auc = auc(recall_curve, precision_curve)

    # Calculate ROC-AUC
    roc_auc = roc_auc_score(y_test, y_prob)

    # Calculate False Positive Cost (example: $100 per False Positive, $1000 per False Negative)
    # Adjust these costs based on business requirements
    fp_cost_per_instance = 100
    fn_cost_per_instance = 1000
    total_fp_cost = fp * fp_cost_per_instance
    total_fn_cost = fn * fn_cost_per_instance
    total_misclassification_cost = total_fp_cost + total_fn_cost

    return {
        'Model': model_name,
        'Precision (Fraud)': precision_fraud,
        'Recall (Fraud)': recall_fraud,
        'F1-Score (Fraud)': f1_score_fraud,
        'PR-AUC': pr_auc,
        'ROC-AUC': roc_auc,
        'False Positives': fp,
        'False Negatives': fn,
        'Total FP Cost ($)': total_fp_cost,
        'Total FN Cost ($)': total_fn_cost,
        'Total Misclassification Cost ($)': total_misclassification_cost
    }

# --- Get metrics for each best model ---

# Logistic Regression (from RandomizedSearchCV)
lr_metrics = get_model_metrics(best_model_lr_rs, X_test_scaled, y_test, 'Logistic Regression (Tuned)')

# Neural Network (from Bayesian Optimization)
# For Keras models, predict_proba is not directly available, use predict and flatten
# Ensure X_test_scaled is converted to a numpy array for Keras predict if it's a DataFrame
if isinstance(X_test_scaled, pd.DataFrame):
    X_test_scaled_np = X_test_scaled.to_numpy()
else:
    X_test_scaled_np = X_test_scaled

# Keras models from tuner.get_best_models() do not have predict_proba, use predict
y_prob_best_nn_for_metrics = best_model_nn.predict(X_test_scaled_np).flatten()

# Temporarily modify get_model_metrics or pass y_prob directly for NN
def get_nn_metrics(model, X_test, y_test, model_name, y_prob_nn):
    y_pred = (y_prob_nn > 0.5).astype(int)
    cm = confusion_matrix(y_test, y_pred)
    tn, fp, fn, tp = cm.ravel()
    report = classification_report(y_test, y_pred, output_dict=True, zero_division=0)
    precision_fraud = report['1']['precision']
    recall_fraud = report['1']['recall']
    f1_score_fraud = report['1']['f1-score']
    precision_curve, recall_curve, _ = precision_recall_curve(y_test, y_prob_nn)
    pr_auc = auc(recall_curve, precision_curve)
    roc_auc = roc_auc_score(y_test, y_prob_nn)
    fp_cost_per_instance = 100
    fn_cost_per_instance = 1000
    total_fp_cost = fp * fp_cost_per_instance
    total_fn_cost = fn * fn_cost_per_instance
    total_misclassification_cost = total_fp_cost + total_fn_cost
    return {
        'Model': model_name,
        'Precision (Fraud)': precision_fraud,
        'Recall (Fraud)': recall_fraud,
        'F1-Score (Fraud)': f1_score_fraud,
        'PR-AUC': pr_auc,
        'ROC-AUC': roc_auc,
        'False Positives': fp,
        'False Negatives': fn,
        'Total FP Cost ($)': total_fp_cost,
        'Total FN Cost ($)': total_fn_cost,
        'Total Misclassification Cost ($)': total_misclassification_cost
    }

nn_metrics = get_nn_metrics(best_model_nn, X_test_scaled_np, y_test, 'Neural Network (Tuned)', y_prob_best_nn_for_metrics)

# XGBoost (from GridSearchCV)
xgb_metrics = get_model_metrics(best_model_xgb, X_test_scaled, y_test, 'XGBoost (Tuned)')

# --- Create a comparison DataFrame ---
comparison_df = pd.DataFrame([lr_metrics, nn_metrics, xgb_metrics])

# Display the DataFrame
print("\n--- Model Comparison Summary ---")
display(comparison_df.round(4))

import matplotlib.pyplot as plt
import seaborn as sns

# Prepare data for plotting
plot_df = comparison_df.set_index('Model')

# Define metrics to plot
metrics_to_plot = [
    'Precision (Fraud)',
    'Recall (Fraud)',
    'F1-Score (Fraud)',
    'ROC-AUC',
    'PR-AUC',
    'Total Misclassification Cost ($)'
]

fig, axes = plt.subplots(nrows=len(metrics_to_plot), ncols=1, figsize=(10, 5 * len(metrics_to_plot)))
fig.suptitle('Model Comparison by Metric', fontsize=16, y=1.02)

for i, metric in enumerate(metrics_to_plot):
    if metric == 'Total Misclassification Cost ($)':
        # For cost, lower is better, so we might want a different palette or order
        sns.barplot(x=plot_df.index, y=metric, data=plot_df, ax=axes[i], palette='viridis_r', hue=plot_df.index, legend=False)
        axes[i].set_ylabel(metric, weight='bold')
        axes[i].ticklabel_format(style='plain', axis='y') # Prevent scientific notation for cost
    else:
        sns.barplot(x=plot_df.index, y=metric, data=plot_df, ax=axes[i], palette='viridis', hue=plot_df.index, legend=False)
        axes[i].set_ylabel(metric, weight='bold')

    axes[i].set_title(f'{metric} Comparison', fontsize=12)
    axes[i].set_xlabel('')
    axes[i].set_ylim(0, plot_df[metric].max() * 1.1) # Set y-limit for better visualization

    # Add value labels on top of bars
    for container in axes[i].containers:
        axes[i].bar_label(container, fmt='%.3f', label_type='edge', padding=3)

plt.tight_layout()
plt.show()

"""## Discussion on Model Performance

Based on the comparison table above, let's analyze the performance of each tuned model:

*   **Precision (Fraud):** This metric is crucial in fraud detection as it tells us how many of the predicted fraudulent transactions are actually fraudulent. A high precision means fewer legitimate customers are inconvenienced by false alarms.
*   **Recall (Fraud):** This measures the model's ability to identify all actual fraudulent transactions. High recall is important to minimize missed fraud cases.
*   **F1-Score (Fraud):** The harmonic mean of precision and recall, providing a balanced measure, especially useful for imbalanced datasets.
*   **PR-AUC (Area Under the Precision-Recall Curve):** A robust metric for imbalanced datasets, as it focuses on the performance of the positive class without being influenced by a large number of true negatives. Higher is better.
*   **ROC-AUC (Area Under the Receiver Operating Characteristic Curve):** While less sensitive to imbalance than accuracy, PR-AUC is generally preferred for highly imbalanced datasets. Higher is better.
*   **False Positives & False Negatives:** These counts directly impact the costs associated with the model's errors.
*   **Total Misclassification Cost:** A critical business metric, calculating the hypothetical financial impact of the model's errors based on defined costs for False Positives (e.g., customer inconvenience, investigation costs) and False Negatives (e.g., lost money due to undetected fraud).

### Confusion Matrix Insights

We observe the confusion matrices for each model. The goal is typically to minimize False Negatives (missed fraud) and False Positives (legitimate transactions flagged as fraud), but often there's a trade-off. For financial fraud, False Negatives can be very costly, so a balance is usually sought.

### Inference Latency

Inference latency refers to the time it takes for a trained model to make a prediction on new, unseen data. This is a critical factor for real-time fraud detection systems.

*   **Logistic Regression:** Generally has the lowest inference latency. It's a simple linear model, so predictions involve a straightforward dot product and sigmoid function, making it very fast. Ideal for high-throughput, low-latency environments.

*   **Neural Networks:** Latency can vary significantly. Simpler, shallower networks (like the one used here) can be relatively fast, but deeper, more complex networks with many layers and parameters can have higher latency. Optimized deployment (e.g., using TensorFlow Lite, ONNX) can reduce this.

*   **XGBoost:** Typically falls between Logistic Regression and complex Neural Networks. While it's an ensemble of decision trees, which are fast individually, predicting with many trees (especially with larger `n_estimators`) can add to latency. However, optimized implementations of XGBoost are often very efficient.

In this context, the **XGBoost model appears to be the most performant** across most metrics, particularly in balancing precision and recall while keeping false positives very low, leading to the lowest total misclassification cost. Its inference latency is also typically acceptable for most real-time applications.

XGBoost demonstrated superior performance compared to Logistic Regression and the Neural Network on this specific dataset primarily due to its inherent strengths in handling tabular, highly imbalanced data and its ensemble learning approach. Here's a breakdown:

Handling Class Imbalance: XGBoost inherently addresses class imbalance effectively through parameters like scale_pos_weight. This allows it to give more importance to the minority class (fraudulent transactions) during training, preventing it from being overwhelmed by the majority class.

Ensemble Learning (Boosting): XGBoost is a gradient boosting algorithm that builds a strong predictive model by combining many weak decision tree models sequentially. Each new tree corrects the errors of the previous ones, leading to a highly accurate model. This iterative error correction is particularly powerful for capturing complex non-linear relationships present in the V features of this dataset.

Non-linear Relationships and Feature Interactions: Unlike Logistic Regression, which is a linear model, XGBoost can capture intricate non-linear relationships and interactions between features without requiring explicit feature engineering. The V features in the credit card fraud dataset are often results of PCA, making their individual interpretations difficult but their complex interactions highly predictive of fraud. XGBoost is adept at finding these.

Robustness to Noise and Outliers: Decision tree-based models like XGBoost are generally more robust to noise and outliers in the data compared to linear models or even some neural networks, which can be sensitive to extreme values.

Optimized Implementation: XGBoost is highly optimized for performance and speed, making it efficient for training on large datasets and providing fast inference, which is crucial for fraud detection systems.

In summary, while Logistic Regression struggled with the non-linearities and severe imbalance, and the Neural Network showed improvement (especially with SMOTE and tuning), XGBoost's boosting architecture, specialized handling of imbalance, and ability to model complex feature interactions allowed it to achieve the best balance of precision and recall for the fraud class, resulting in the lowest false positives and ultimately, the lowest misclassification cost.
"""

import matplotlib.pyplot as plt
import seaborn as sns

# Calculate and plot the confusion matrix for the tuned XGBoost model
plt.figure(figsize=(8, 6))
sns.heatmap(cm_xgb_tuned, annot=True, fmt='d', cmap='Blues', cbar=False,
            xticklabels=['Non-Fraud (0)', 'Fraud (1)'],
            yticklabels=['Non-Fraud (0)', 'Fraud (1)'])
plt.title('Confusion Matrix for Tuned XGBoost Classifier')
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.show()

"""The confusion matrix for the tuned XGBoost model has been plotted. It shows:

True Negatives (Top-Left): 56849 non-fraudulent transactions were correctly identified as non-fraudulent.
False Positives (Top-Right): 15 non-fraudulent transactions were incorrectly flagged as fraudulent. This is a very low number, which is excellent for minimizing customer inconvenience.
False Negatives (Bottom-Left): 16 fraudulent transactions were missed by the model.
True Positives (Bottom-Right): 82 fraudulent transactions were correctly identified as fraudulent.
This confirms the excellent performance of the tuned XGBoost model, particularly its ability to keep false positives very low while maintaining a strong recall for detecting actual fraud.
"""

import shutil

# Source file is the best XGBoost model saved previously
source_model_path = 'best_xgboost_model.joblib'

# Destination for the final model
final_model_path = 'final_model.joblib'

# Copy the best XGBoost model to the final model path
shutil.copy(source_model_path, final_model_path)

print(f"Best model (XGBoost) saved as final_model.joblib at: {final_model_path}")

"""## Load and Use the Final Model for Predictions

To use the saved `final_model.joblib` for new predictions, you first need to load it back into memory. Then, you can pass new, unseen data (which should be preprocessed in the same way as your training data) to the model's `predict` or `predict_proba` method.
"""

import joblib
import pandas as pd

# Load the final model
loaded_model = joblib.load('final_model.joblib')

print('Final model loaded successfully!')

# Example of new data (replace with actual new data)
# This 'new_transaction' should be preprocessed in the same way your training data was.
# For demonstration, we'll create a synthetic new transaction using the mean of X_test_scaled.
# In a real scenario, you would have actual new transaction data to preprocess and predict.

# Using the first row of X_test_scaled as an example for 'new data'
# In a real application, you would preprocess new raw data (e.g., scale 'Time' and 'Amount')
# before feeding it to the model.
new_transaction_scaled = X_test_scaled.iloc[[0]]

print('\nMaking a prediction on a sample new transaction:')
display(new_transaction_scaled)

# Make a prediction
prediction = loaded_model.predict(new_transaction_scaled)
prediction_proba = loaded_model.predict_proba(new_transaction_scaled)[:, 1]

print(f"\nPredicted class: {prediction[0]} (0: Non-Fraud, 1: Fraud)")
print(f"Predicted probability of fraud: {prediction_proba[0]:.4f}")

# You can also set a custom threshold if needed
custom_threshold = 0.5 # or any other threshold you optimized for
predicted_class_threshold = (prediction_proba[0] >= custom_threshold).astype(int)
print(f"Predicted class with custom threshold {custom_threshold}: {predicted_class_threshold} (0: Non-Fraud, 1: Fraud)")

"""## Create a Lightweight Demo API for the Model

We will create a simple Flask API that loads the `final_model.joblib` and exposes an endpoint for making predictions. This API will include the necessary preprocessing (scaling 'Time' and 'Amount') before passing the data to the model.

First, let's ensure the `scaler` used during training is also saved and loaded with the model, or recreated with the same parameters. For simplicity and to match the existing notebook's state, I'll assume the `scaler` object (which was `StandardScaler` fitted on `X_train[['Time', 'Amount']]`) is implicitly available or re-initialized with the correct training parameters. In a production scenario, you would save the scaler as well.

For this demo, we'll recreate the scaler and fit it on the original `X_train[['Time', 'Amount']]` to ensure consistent scaling. Then, we will create `app.py`.
"""

# Re-initialize and fit the StandardScaler as it was used during training
from sklearn.preprocessing import StandardScaler

# Assuming X_train from earlier in the notebook is available
# In a real deployment, you would save and load the fitted scaler.
# For this demo, we'll re-fit it to ensure it's available.

scaler_for_api = StandardScaler()
scaler_for_api.fit(X_train[['Time', 'Amount']])

# Now, write the app.py content to a file
app_content = """
from flask import Flask, request, jsonify
import joblib
import pandas as pd
from sklearn.preprocessing import StandardScaler # For preprocessing

app = Flask(__name__)

# Load the trained model
model = joblib.load('final_model.joblib')

# Assuming the scaler was fitted on 'Time' and 'Amount' from the training data
# In a real deployment, you would save and load the fitted scaler.
# For this example, we re-initialize and fit on dummy data to match structure.
# Ideally, this scaler object would also be serialized and loaded.

# Create a dummy scaler object for demonstration. THIS SHOULD BE YOUR *FITTED* SCALER.
# In a production setup, you would load the actual fitted scaler.
# For this demo, we will use a global scaler object that was fitted earlier in the notebook.
# In a complete standalone API, you would save and load the fitted scaler, not re-fit it.
# For the purpose of this Colab demo, we will assume `scaler_for_api` is the one from the notebook state.

# Replace this with the actual loaded scaler from your workflow
# For the context of this Colab, we'll make the scaler global to match the existing notebook
global_scaler = None

@app.before_first_request
def load_global_scaler():
    global global_scaler
    # This part should be replaced by loading your *saved* scaler, e.g., joblib.load('scaler.joblib')
    # For this demo, we are using the scaler object generated in the cell above.
    # In a real scenario, the scaler would be saved after fitting and loaded here.
    global_scaler = joblib.load('scaler_for_api.joblib') # Assuming you saved it
    print("Scaler loaded successfully within Flask app!")

@app.route('/predict', methods=['POST'])
def predict():
    try:
        data = request.get_json(force=True)
        df = pd.DataFrame([data])

        # Ensure the columns are in the same order as the training data
        # This is critical for consistent predictions
        # Assuming X_train_scaled.columns is the correct order
        # In a production API, you would predefine this order or validate input.
        expected_columns = model.feature_names_in_ # Get feature names from the fitted XGBoost model
        df = df[expected_columns]

        # Apply the same scaling as during training
        # Assuming 'Time' and 'Amount' were scaled
        if global_scaler is None:
             return jsonify({'error': 'Scaler not loaded'}), 500

        df[['Time', 'Amount']] = global_scaler.transform(df[['Time', 'Amount']])

        # Make prediction
        prediction = model.predict(df)
        prediction_proba = model.predict_proba(df)[:, 1]

        return jsonify({"prediction": int(prediction[0]), "fraud_probability": float(prediction_proba[0])})

    except Exception as e:
        return jsonify({"error": str(e)}), 400

if __name__ == '__main__':
    # For deployment, use a production-ready WSGI server like Gunicorn
    # For local testing, you can run:
    # flask run --host=0.0.0.0 --port=5000
    # Or directly using app.run() in development mode (not recommended for production)
    app.run(host='0.0.0.0', port=5000)
"""

# Save the scaler used for API preprocessing
joblib.dump(scaler_for_api, 'scaler_for_api.joblib')

# Write the Flask app content to a file named app.py
with open('app.py', 'w') as f:
    f.write(app_content)

print("Flask API 'app.py' created and 'scaler_for_api.joblib' saved!")

"""### How to Run the API

To run this Flask API locally or in a deployment environment (like on a cloud VM), follow these steps:

1.  **Save the `app.py` file** (which was created in the previous cell) and `final_model.joblib` (which was created earlier) and `scaler_for_api.joblib` (which was created in the previous cell) in the same directory.
2.  **Install Flask and Gunicorn** (Gunicorn is a production-ready WSGI server, recommended over Flask's built-in server for production):
    ```bash
    pip install Flask gunicorn pandas scikit-learn xgboost joblib
    ```
3.  **Run the API:**
    *   **For local testing/development (not recommended for production):**
        ```bash
        python app.py
        ```
    *   **For production (using Gunicorn):**
        ```bash
        gunicorn --bind 0.0.0.0:5000 app:app
        ```
    The API will be running on `http://0.0.0.0:5000`.

### How to Test the API (from Colab or another client)

You can send a POST request to the `/predict` endpoint with your new transaction data. The data should be a JSON object containing the features of the transaction, similar to how your `X_test` data was structured (excluding 'Class').

Let's demonstrate sending a sample request to the running API (assuming it's accessible at `http://localhost:5000` or a public IP if deployed).

## README: Fraud Detection API

This document outlines the setup, deployment, and usage of the Fraud Detection API. This API uses a pre-trained XGBoost model to predict the likelihood of a transaction being fraudulent based on transaction features.

### 1. Project Objective

To develop a fraud detection pipeline that predicts fraud probability, evaluates performance using imbalanced classification metrics, and exposes predictions through a simple API.

### 2. Model

The final model used in this API is a **Tuned XGBoost Classifier**, saved as `final_model.joblib`. It was selected due to its superior performance in balancing precision and recall, and minimizing false positives on the highly imbalanced credit card fraud dataset. A `StandardScaler` (`scaler_for_api.joblib`) is used for preprocessing the `Time` and `Amount` features, as was done during model training.

### 3. API Endpoints

The API provides the following endpoint:

*   **`/predict` (POST)**: Accepts transaction data as a JSON payload and returns a fraud prediction (0 for non-fraud, 1 for fraud) along with the probability of fraud.

### 4. Setup and Dependencies

To set up and run the API, ensure you have Python 3.8+ installed. Then, follow these steps:

#### A. Prerequisites:

1.  **Model and Scaler Files**: Ensure the `final_model.joblib` and `scaler_for_api.joblib` files are in the same directory as `app.py`. These files should have been generated and saved during the model training and preparation phase in the Colab notebook.

#### B. Installation:

1.  **Clone the repository (if applicable) or create the necessary files:**
    *   Create `app.py` (content generated in the Colab notebook).
    *   Ensure `final_model.joblib` and `scaler_for_api.joblib` are present.
2.  **Install Python dependencies:**

    ```bash
    pip install Flask gunicorn pandas scikit-learn xgboost joblib
    ```

### 5. Running the API

You can run the API either for local development or for production deployment.

#### A. For Local Testing/Development (not recommended for production):

Open your terminal in the directory containing `app.py` and run:

```bash
python app.py
```

The API will be accessible at `http://127.0.0.1:5000`.

#### B. For Production (using Gunicorn):

For a more robust and production-ready deployment, use Gunicorn:

Open your terminal in the directory containing `app.py` and run:

```bash
gunicorn --bind 0.0.0.0:5000 app:app
```

The API will be accessible on port `5000` of the host it's running on (e.g., `http://your-server-ip:5000`).

### 6. Testing the API

Once the API is running, you can send POST requests to the `/predict` endpoint. The request body should be a JSON object containing the 30 features of a transaction (`Time`, `V1` through `V28`, and `Amount`).

#### A. Example Request Structure:

```json
{
  "Time": 12345.0,
  "V1": -1.359807,
  "V2": -0.072781,
  "V3": 2.536347,
  "V4": 1.378155,
  "V5": -0.338320,
  "V6": 0.462388,
  "V7": 0.239599,
  "V8": 0.098698,
  "V9": 0.363787,
  "V10": 0.090794,
  "V11": -0.551600,
  "V12": -0.617801,
  "V13": -0.991390,
  "V14": -0.311169,
  "V15": 1.468177,
  "V16": -0.470401,
  "V17": 0.207971,
  "V18": 0.025791,
  "V19": 0.403993,
  "V20": 0.251412,
  "V21": -0.018307,
  "V22": 0.277838,
  "V23": -0.110474,
  "V24": 0.066928,
  "V25": 0.128539,
  "V26": -0.189115,
  "V27": 0.133558,
  "V28": -0.021053,
  "Amount": 149.62
}
```

#### B. Sample Predictions (using `requests` in Python):

To test the API programmatically, you would use a library like `requests`. Replace `http://localhost:5000/predict` with the actual URL where your API is running.

```python
import requests
import json

api_url = 'http://localhost:5000/predict' # Or your deployed API URL
headers = {'Content-Type': 'application/json'}

def send_prediction_request(transaction_data):
    try:
        response = requests.post(api_url, data=json.dumps(transaction_data), headers=headers)
        response.raise_for_status() # Raise HTTPError for bad responses (4xx or 5xx)
        return response.json()
    except requests.exceptions.ConnectionError:
        print("Error: Could not connect to the API. Is it running?")
        return None
    except requests.exceptions.RequestException as e:
        print(f"An error occurred: {e}")
        return None

# --- Sample 1: Non-Fraudulent Transaction (from X_test, Class 0) ---
# Example using the first row of X_test from the Colab notebook (actual class: 0)
sample_non_fraud = {
  "Time": 160760.0,
  "V1": -0.674466064578314,
  "V2": 1.40810501967799,
  "V3": -1.11062205357093,
  "V4": -1.32836577843066,
  "V5": 1.38899603254837,
  "V6": -1.30843906707795,
  "V7": 1.88587890268717,
  "V8": -0.614232966299775,
  "V9": 0.311652212453101,
  "V10": 0.65075700363522,
  "V11": -0.857784661547805,
  "V12": -0.229961445775592,
  "V13": -0.19981700479103,
  "V14": 0.266371326329879,
  "V15": -0.0465441684754424,
  "V16": -0.741398089749789,
  "V17": -0.605616644106022,
  "V18": -0.39256818789208,
  "V19": -0.162648311024695,
  "V20": 0.394321820843914,
  "V21": 0.0800842396026648,
  "V22": 0.810033595602455,
  "V23": -0.224327230436412,
  "V24": 0.707899237446867,
  "V25": -0.13583702273753,
  "V26": 0.0451021964988772,
  "V27": 0.533837219064273,
  "V28": 0.291319252625364,
  "Amount": 23.0
}
print("\n--- Testing Non-Fraudulent Transaction ---")
response = send_prediction_request(sample_non_fraud)
if response: print(json.dumps(response, indent=2))

# --- Sample 2: Another Non-Fraudulent Transaction (from X_test, Class 0) ---
sample_non_fraud_2 = {
  "Time": 406.0,
  "V1": -2.312226542,
  "V2": 1.951992011,
  "V3": -1.609850731,
  "V4": 3.997906069,
  "V5": -0.522187864,
  "V6": -1.426545318,
  "V7": -2.537387306,
  "V8": 1.391657252,
  "V9": -2.770089277,
  "V10": -2.772272145,
  "V11": 3.202033207,
  "V12": -2.899907385,
  "V13": -0.592509655,
  "V14": -4.289253753,
  "V15": 0.38972412,
  "V16": -1.140747185,
  "V17": -2.830055675,
  "V18": -0.016822468,
  "V19": 0.416956198,
  "V20": 0.126910543,
  "V21": 0.517232371,
  "V22": -0.035049368,
  "V23": -0.465211076,
  "V24": 0.320198199,
  "V25": 0.044519356,
  "V26": 0.177839798,
  "V27": 0.261145003,
  "V28": 0.143681423,
  "Amount": 99.0
}
print("\n--- Testing Another Non-Fraudulent Transaction ---")
response = send_prediction_request(sample_non_fraud_2)
if response: print(json.dumps(response, indent=2))

# --- Sample 3: Fraudulent Transaction (from X_test, Class 1) ---
# Example using a known fraudulent transaction (e.g., from X_test where y_test == 1)
sample_fraud = {
  "Time": 472.0,
  "V1": -3.043541334,
  "V2": 3.156179352,
  "V3": -3.213537651,
  "V4": 3.333256037,
  "V5": 2.710898516,
  "V6": -0.466906204,
  "V7": -0.27962483,
  "V8": -1.002212354,
  "V9": 0.697576059,
  "V10": -1.632679237,
  "V11": 0.36350478,
  "V12": -0.748530366,
  "V13": -0.009949673,
  "V14": -0.430459345,
  "V15": 1.157850117,
  "V16": -0.662137976,
  "V17": 0.167444318,
  "V18": 0.162747754,
  "V19": -0.198271501,
  "V20": 0.264561858,
  "V21": 0.661969248,
  "V22": 0.052824982,
  "V23": -0.207963384,
  "V24": -0.071624686,
  "V25": 0.252934812,
  "V26": 0.399710356,
  "V27": 0.141045763,
  "V28": 0.265415307,
  "Amount": 1.0
}
print("\n--- Testing Fraudulent Transaction ---")
response = send_prediction_request(sample_fraud)
if response: print(json.dumps(response, indent=2))

# --- Known Failure Case: Missing a required feature ---
# The API expects all 30 features. Missing one should result in an error.
print("\n--- Testing Failure Case (Missing Feature) ---")
failure_case_data = {
  "Time": 123.0,
  "V1": 0.0,
  "V2": 0.0,
  "Amount": 10.0
  # Many V-features are intentionally missing
}
response = send_prediction_request(failure_case_data)
if response: print(json.dumps(response, indent=2))

# --- Known Failure Case: Invalid data type ---
# Sending a string for a numerical feature should result in an error.
print("\n--- Testing Failure Case (Invalid Data Type) ---")
failure_case_data_2 = {
  "Time": "invalid",
  "V1": -1.359807,
  "V2": -0.072781,
  "V3": 2.536347,
  "V4": 1.378155,
  "V5": -0.338320,
  "V6": 0.462388,
  "V7": 0.239599,
  "V8": 0.098698,
  "V9": 0.363787,
  "V10": 0.090794,
  "V11": -0.551600,
  "V12": -0.617801,
  "V13": -0.991390,
  "V14": -0.311169,
  "V15": 1.468177,
  "V16": -0.470401,
  "V17": 0.207971,
  "V18": 0.025791,
  "V19": 0.403993,
  "V20": 0.251412,
  "V21": -0.018307,
  "V22": 0.277838,
  "V23": -0.110474,
  "V24": 0.066928,
  "V25": 0.128539,
  "V26": -0.189115,
  "V27": 0.133558,
  "V28": -0.021053,
  "Amount": 149.62
}
response = send_prediction_request(failure_case_data_2)
if response: print(json.dumps(response, indent=2))
```

#### C. Fraud Risk Interpretation

The API returns a `fraud_probability` which is a float value between 0 and 1. A value closer to 1 indicates a higher probability of the transaction being fraudulent, while a value closer to 0 indicates a lower probability. The `prediction` field provides a binary classification (0 or 1) based on a default threshold (usually 0.5, but adjustable if needed) applied to this probability.

### 7. Deployment Considerations

*   **Scalability**: For high-traffic applications, consider deploying the API using containerization technologies (e.g., Docker) and orchestration platforms (e.g., Kubernetes) on cloud providers (GCP, AWS, Azure).
*   **Security**: Implement API key authentication, HTTPS, and proper access controls to secure your API endpoints.
*   **Monitoring**: Set up logging and monitoring to track API performance, errors, and model predictions in real-time.
*   **Environment Variables**: Use environment variables to manage sensitive information or configuration settings (e.g., model paths, thresholds) rather than hardcoding them in `app.py`.

### 8. Further Enhancements

*   **Error Handling**: Implement more granular error handling and specific error codes.
*   **Input Validation**: Add more robust input validation to ensure incoming data conforms to expected types and ranges.
*   **Explainability**: Integrate model interpretability techniques (e.g., SHAP, LIME) to provide reasons for fraud predictions, which can be crucial for investigations.

### 9. Deploying and Testing with Docker

To containerize your application for consistent deployment across different environments, you can use Docker. Follow these steps to build a Docker image, run a container, and test your API.

#### A. Create a `Dockerfile`

Create a file named `Dockerfile` (no extension) in the same directory as `app.py`, `final_model.joblib`, and `scaler_for_api.joblib`. Its content should be as follows:
"""

dockerfile_content = """
# Use an official Python runtime as a parent image
FROM python:3.9-slim-buster

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Make port 5000 available to the world outside this container
EXPOSE 5000

# Define environment variable
ENV NAME World

# Run app.py when the container launches
CMD ["gunicorn", "--bind", "0.0.0.0:5000", "app:app"]
"""

with open('Dockerfile', 'w') as f:
    f.write(dockerfile_content)

print("Dockerfile created successfully with requirements.txt!")

"""#### B. Build the Docker Image

Open your terminal, navigate to the directory where you saved `Dockerfile`, `app.py`, `final_model.joblib`, and `scaler_for_api.joblib`. Then, build the Docker image:

```bash
docker build -t fraud-detection-api .
```

This command builds an image named `fraud-detection-api` from the `Dockerfile` in the current directory (`.`).

#### C. Run the Docker Container

Once the image is built, run a container from it, mapping port `5000` from the container to port `5000` on your host machine:

```bash
docker run -d -p 5000:5000 --name fraud-api-container fraud-detection-api
```

*   `-d`: Runs the container in detached mode (in the background).
*   `-p 5000:5000`: Maps port 5000 of the host to port 5000 of the container.
*   `--name fraud-api-container`: Assigns a name to your container for easier management.

#### D. Test the API in Docker

Now, with the Docker container running, you can send requests to your API from your host machine. You can use `curl` in your terminal or the Python `requests` library.

**Using `curl` (in your terminal):**

```bash
curl -X POST -H "Content-Type: application/json" -d '{
  "Time": 160760.0,
  "V1": -0.674466064578314,
  "V2": 1.40810501967799,
  "V3": -1.11062205357093,
  "V4": -1.32836577843066,
  "V5": 1.38899603254837,
  "V6": -1.30843906707795,
  "V7": 1.88587890268717,
  "V8": -0.614232966299775,
  "V9": 0.311652212453101,
  "V10": 0.65075700363522,
  "V11": -0.857784661547805,
  "V12": -0.229961445775592,
  "V13": -0.19981700479103,
  "V14": 0.266371326329879,
  "V15": -0.0465441684754424,
  "V16": -0.741398089749789,
  "V17": -0.605616644106022,
  "V18": -0.39256818789208,
  "V19": -0.162648311024695,
  "V20": 0.394321820843914,
  "V21": 0.0800842396026648,
  "V22": 0.810033595602455,
  "V23": -0.224327230436412,
  "V24": 0.707899237446867,
  "V25": -0.13583702273753,
  "V26": 0.0451021964988772,
  "V27": 0.533837219064273,
  "V28": 0.291319252625364,
  "Amount": 23.0
}' http://localhost:5000/predict
```

**Using Python `requests` (similar to previous testing cell):**

```python
import requests
import json

api_url_docker = 'http://localhost:5000/predict' # API running in Docker
headers = {'Content-Type': 'application/json'}

def send_prediction_request_docker(transaction_data):
    try:
        response = requests.post(api_url_docker, data=json.dumps(transaction_data), headers=headers)
        response.raise_for_status() # Raise HTTPError for bad responses (4xx or 5xx)
        return response.json()
    except requests.exceptions.ConnectionError:
        print("Error: Could not connect to the API. Is the Docker container running?")
        return None
    except requests.exceptions.RequestException as e:
        print(f"An error occurred: {e}")
        return None

# Example using one of the sample transactions from your README:
sample_non_fraud_docker = {
  "Time": 160760.0,
  "V1": -0.674466064578314,
  "V2": 1.40810501967799,
  "V3": -1.11062205357093,
  "V4": -1.32836577843066,
  "V5": 1.38899603254837,
  "V6": -1.30843906707795,
  "V7": 1.88587890268717,
  "V8": -0.614232966299775,
  "V9": 0.311652212453101,
  "V10": 0.65075700363522,
  "V11": -0.857784661547805,
  "V12": -0.229961445775592,
  "V13": -0.19981700479103,
  "V14": 0.266371326329879,
  "V15": -0.0465441684754424,
  "V16": -0.741398089749789,
  "V17": -0.605616644106022,
  "V18": -0.39256818789208,
  "V19": -0.162648311024695,
  "V20": 0.394321820843914,
  "V21": 0.0800842396026648,
  "V22": 0.810033595602455,
  "V23": -0.224327230436412,
  "V24": 0.707899237446867,
  "V25": -0.13583702273753,
  "V26": 0.0451021964988772,
  "V27": 0.533837219064273,
  "V28": 0.291319252625364,
  "Amount": 23.0
}

print("\n--- Testing API in Docker ---")
response = send_prediction_request_docker(sample_non_fraud_docker)
if response: print(json.dumps(response, indent=2))
```

#### E. Clean Up Docker Resources (Optional)

When you're done, you can stop and remove the container and image:

```bash
docker stop fraud-api-container
docker rm fraud-api-container
docker rmi fraud-detection-api
```
"""

import requests
import json

api_url_docker = 'http://localhost:5000/predict' # API running in Docker
headers = {'Content-Type': 'application/json'}

def send_prediction_request_docker(transaction_data):
    try:
        response = requests.post(api_url_docker, data=json.dumps(transaction_data), headers=headers)
        response.raise_for_status() # Raise HTTPError for bad responses (4xx or 5xx)
        return response.json()
    except requests.exceptions.ConnectionError:
        print("Error: Could not connect to the API. Is the Docker container running?")
        return None
    except requests.exceptions.RequestException as e:
        print(f"An error occurred: {e}")
        return None

# Example using one of the sample transactions from your README:
sample_non_fraud_docker = {
  "Time": 160760.0,
  "V1": -0.674466064578314,
  "V2": 1.40810501967799,
  "V3": -1.11062205357093,
  "V4": -1.32836577843066,
  "V5": 1.38899603254837,
  "V6": -1.30843906707795,
  "V7": 1.88587890268717,
  "V8": -0.614232966299775,
  "V9": 0.311652212453101,
  "V10": 0.65075700363522,
  "V11": -0.857784661547805,
  "V12": -0.229961445775592,
  "V13": -0.19981700479103,
  "V14": 0.266371326329879,
  "V15": -0.0465441684754424,
  "V16": -0.741398089749789,
  "V17": -0.605616644106022,
  "V18": -0.39256818789208,
  "V19": -0.162648311024695,
  "V20": 0.394321820843914,
  "V21": 0.0800842396026648,
  "V22": 0.810033595602455,
  "V23": -0.224327230436412,
  "V24": 0.707899237446867,
  "V25": -0.13583702273753,
  "V26": 0.0451021964988772,
  "V27": 0.533837219064273,
  "V28": 0.291319252625364,
  "Amount": 23.0
}

print("\n--- Testing API in Docker ---")
response = send_prediction_request_docker(sample_non_fraud_docker)
if response: print(json.dumps(response, indent=2))

import requests
import json
import pandas as pd

# Define the API endpoint URL
# Adjust this if your API is running on a different host or port.
# If testing a Docker container, it's typically 'http://localhost:5000/predict'
# If running directly with `python app.py` on your machine, it's 'http://127.0.0.1:5000/predict'
api_url = 'http://localhost:5000/predict' # Default for Docker testing
headers = {'Content-Type': 'application/json'}

def send_prediction_request(transaction_data):
    """Sends a POST request to the API and handles potential errors."""
    try:
        response = requests.post(api_url, data=json.dumps(transaction_data), headers=headers)
        response.raise_for_status() # Raise HTTPError for bad responses (4xx or 5xx)
        print("API Response:")
        print(json.dumps(response.json(), indent=2))
    except requests.exceptions.ConnectionError:
        print("Error: Could not connect to the API. Is the API running at `" + api_url + "`?")
    except requests.exceptions.RequestException as e:
        print(f"An error occurred: {e}")
    print("\n" + "="*50 + "\n") # Separator for readability


print("Starting API Scenario Testing...\n" + "="*50 + "\n")

# --- Scenario 1: Non-Fraudulent Transaction (expected Class 0) ---
# Using the first row of X_test from the Colab notebook (actual class: 0)
# Ensure this data is RAW (not scaled), as the API will handle scaling.
sample_non_fraud = X_test.iloc[0].to_dict()
for key, value in sample_non_fraud.items(): # Convert numpy types for JSON serialization
    if hasattr(value, 'item'):
        sample_non_fraud[key] = value.item()

print("--- Testing Scenario 1: Known Non-Fraudulent Transaction (Expected: Non-Fraud) ---")
send_prediction_request(sample_non_fraud)

# --- Scenario 2: Another Non-Fraudulent Transaction (expected Class 0) ---
sample_non_fraud_2 = X_test.iloc[1].to_dict()
for key, value in sample_non_fraud_2.items(): # Convert numpy types for JSON serialization
    if hasattr(value, 'item'):
        sample_non_fraud_2[key] = value.item()

print("--- Testing Scenario 2: Another Known Non-Fraudulent Transaction (Expected: Non-Fraud) ---")
send_prediction_request(sample_non_fraud_2)

# --- Scenario 3: Fraudulent Transaction (expected Class 1) ---
# Find a known fraudulent transaction from the test set for realistic testing
fraud_idx = y_test[y_test == 1].index[0] # Get the index of the first fraudulent transaction
sample_fraud = X_test.loc[fraud_idx].to_dict()
for key, value in sample_fraud.items(): # Convert numpy types for JSON serialization
    if hasattr(value, 'item'):
        sample_fraud[key] = value.item()

print("--- Testing Scenario 3: Known Fraudulent Transaction (Expected: Fraud) ---")
send_prediction_request(sample_fraud)

# --- Scenario 4: Failure Case - Missing a required feature ---
# The API expects all 30 features. Missing one should result in an error.
print("--- Testing Scenario 4: Failure Case (Missing Feature) ---")
failure_case_data_missing_feature = {
  "Time": 123.0,
  "V1": 0.0,
  "V2": 0.0,
  "Amount": 10.0
  # Many V-features are intentionally missing
}
send_prediction_request(failure_case_data_missing_feature)

# --- Scenario 5: Failure Case - Invalid data type ---
# Sending a string for a numerical feature should result in an error.
print("--- Testing Scenario 5: Failure Case (Invalid Data Type for 'Time') ---")
failure_case_data_invalid_type = sample_non_fraud.copy()
failure_case_data_invalid_type['Time'] = "invalid_time"
send_prediction_request(failure_case_data_invalid_type)

print("All API testing scenarios completed.")

"""#### E. Clean Up Docker Resources

When you're done, you can stop and remove the container and image:

```bash
docker stop fraud-api-container
docker rm fraud-api-container
docker rmi fraud-detection-api
```
"""

import requests
import json
import pandas as pd

# Define the API endpoint URL
# If running locally in Colab, you would need to use a tool like ngrok
# to expose your local Flask server to a public URL. For a true local test
# if you were running this in a terminal, you'd use 'http://127.0.0.1:5000/predict'.
# For this demonstration, we'll simulate the API call and expected output.

# We'll use a sample transaction from X_test_scaled (the first row)
# In a real scenario, this would be raw data that the API preprocesses.

# Get a sample transaction (raw data, not scaled, so the API can scale it)
# We need a sample from X_test or X_train before scaling for this demo.
# Let's pick a row from the original X_test for demonstration.

sample_raw_transaction = X_test.iloc[0].to_dict()

# Convert numpy types to native Python types for JSON serialization
for key, value in sample_raw_transaction.items():
    if isinstance(value, (pd.Timestamp, pd.Timedelta)):
        sample_raw_transaction[key] = str(value)
    elif hasattr(value, 'item'): # For numpy scalars
        sample_raw_transaction[key] = value.item()

print("Sample raw transaction to send:")
print(json.dumps(sample_raw_transaction, indent=2))

# Simulate API call (since we can't directly run a Flask server and call it in the same Colab kernel easily)
# In a real scenario, you would uncomment and run the requests.post part.

# api_url = 'http://127.0.0.1:5000/predict' # Replace with your actual API URL
# headers = {'Content-Type': 'application/json'}

# try:
#     response = requests.post(api_url, data=json.dumps(sample_raw_transaction), headers=headers)
#     response.raise_for_status() # Raise an exception for HTTP errors
#     prediction_result = response.json()
#     print("\nAPI Response:")
#     print(json.dumps(prediction_result, indent=2))
# except requests.exceptions.ConnectionError:
#     print("\nError: Could not connect to the Flask API. Is it running?")
# except requests.exceptions.RequestException as e:
#     print(f"\nAn error occurred: {e}")

# Since we cannot run Flask server in Colab easily, we'll manually predict to show expected output
print("\n--- Simulating API Prediction Locally ---")
# The actual prediction if the API was running and called successfully

# Preprocess the sample transaction using the global_scaler (which would be loaded in the API)
# This re-uses the scaler_for_api object from the previous cell
processed_sample = pd.DataFrame([sample_raw_transaction])
processed_sample_scaled = processed_sample.copy()
processed_sample_scaled[['Time', 'Amount']] = scaler_for_api.transform(processed_sample[['Time', 'Amount']])

# Ensure columns are in the same order as model.feature_names_in_
# Use loaded_model instead of model
expected_columns = loaded_model.feature_names_in_
processed_sample_scaled = processed_sample_scaled[expected_columns]

simulated_prediction = loaded_model.predict(processed_sample_scaled)[0]
simulated_probability = loaded_model.predict_proba(processed_sample_scaled)[:, 1][0]

print(f"Simulated Prediction (0: Non-Fraud, 1: Fraud): {int(simulated_prediction)}")
print(f"Simulated Fraud Probability: {simulated_probability:.4f}")

print("\nNote: To truly test the API, you would need to deploy it (e.g., to a cloud service, or expose it via ngrok for local testing).")

import sys

# Generate requirements.txt using pip freeze
!{sys.executable} -m pip freeze > requirements.txt

print("Generated requirements.txt")

# Display the content of requirements.txt
with open('requirements.txt', 'r') as f:
    requirements_content = f.read()
print(requirements_content)

